### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by karimovaSvetlana** [lene/DuplicateImages#11]
**Command:** find-dups -h

**Gives an error:**
Traceback (most recent call last):
  File "/usr/local/bin/find-dups", line 5, in <module>
    from duplicate_images.duplicate import main
  File "/usr/local/lib/python3.9/site-packages/duplicate_images/duplicate.py", line 26, in <module>
    register_heif_opener()
  File "/usr/local/lib/python3.9/site-packages/pillow_heif/as_plugin.py", line 178, in register_heif_opener
    if _pillow_heif.get_lib_info()["HEIF"]:
  File "/usr/local/lib/python3.9/site-packages/pillow_heif/_deffered_error.py", line 11, in __getattr__
    raise self.ex
  File "/usr/local/lib/python3.9/site-packages/pillow_heif/as_plugin.py", line 25, in <module>
    import _pillow_heif
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/_pillow_heif.cpython-39-darwin.so, 2): **Symbol not found: __ZTTNSt3__118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE**
  Referenced from: /usr/local/lib/python3.9/site-packages/pillow_heif/.dylibs/libde265.0.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /usr/local/lib/python3.9/site-packages/pillow_heif/.dylibs/libde265.0.dylib

**Comment by lene** [comment]
Thank you for the bug report! This looks very much like a bug in the [pillow_heif](https://github.com/bigcat88/pillow_heif) module I am using to open HEIF images, or in its dependency [libde265](https://github.com/strukturag/libde265). I will update the dependencies to the newest versions and hope that solves the issue, or otherwise report an upstream bug.
Do you want to run the program on HEIF encoded images, or would you be content if HEIF support would not work for you?

**Comment by lene** [comment]
Released a new version, 0.11.1. If you'd like to do me a favor, please test the new version by running 
```
$ pip install --upgrade duplicate_images
``` 
and report back to me whether, when running `$ find-dups -h` again, you receive a warning that says `HEIF support not available`. If that is the case, I will report the problem to the maintainer of the `pillow_heif` module!

**Comment by lene** [comment]
Closing because no further feedback, assuming solved
